export interface VaultConfig {
  id: string;
  name: string;
  token: string;
  tokenDescription: string;
  tokenAddress: string;
  tokenDecimals: number;
  tokenDescriptionUrl: string;
  earnedToken: string;
  earnedTokenAddress: string;
  earnContractAddress: string;
  pricePerFullShare: number;
  tvl: number;
  oracle: string;
  oracleId: string;
  oraclePrice: number;
  depositsPaused: boolean;
  status: string;
  platform: string;
  assets: string[];
  risks: string[];
  stratType: string;
  depositFee: string;
  withdrawalFee: string;
  addLiquidityUrl: string;
  retireReason: string;
  buyTokenUrl: string;
  createdAt: number;
}
