[profile.default]
src = "contracts/src"
test = "contracts/test"
script = "contracts/script"
out = "contracts/out"
cache_path = "contracts/cache"
libs = ["node_modules", "contracts/lib"]
ignored_error_codes = [
    #"license",
    #"code-size",
    #"init-code-size",
]
deny_warnings = true

[profile.gas-optimize]
solc_version = '0.8.21'
optimizer = true
optimizer_runs = 200_000_000
via_ir = true

[profile.gas-optimize.optimizer_details]
inliner = true
deduplicate = true
constantOptimizer = true
# yul = true # makes it worse
# orderLiterals = true # makes it worse
# cse = true # makes it worse